services:
  - type: web
    name: link-remover-bot
    env: python
    plan: free
    repo: https://github.com/youruser/link_remover_bot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
      - key: WEBHOOK_URL
      
